/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

// Generated by toolkit/components/pdfjs/update.sh, do not edit by hand.
export const PDFJS_VERSION = "6.3.335";
