name: Fetch latest Firefox src

on:
  schedule:
    - cron: '35 6 * * 4'
    # * is a special character in YAML so you have to quote this string
    # Thu 06:35
    
  
  workflow_dispatch:

  # push:
  #   branches:
  #     - bot
          

jobs:
  my_first_job_id:
    name: Fetch latest Firefox src
    runs-on: ubuntu-latest
    steps:
    - name: Job's checkout
      uses: actions/checkout@master

    - name: Show some info and switch branch
      run: |
        pwd
        ls -la
        git branch -a
        git fetch origin master
        git branch -a
        git config user.name bot
        git config user.email bot@github.bot.none
        git config --list
        env

    - name: Run the bash
      run: bash ff-src-part-ci.sh
        
